version: '3.8'

services:
  # Redis service for BullMQ
  redis:
    image: redis:7-alpine
    container_name: rinha-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # command: redis-server --appendonly yes --maxmemory 40mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"
    networks:
      - rinha-network

  # Main API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha-api
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
    environment:
      - NODE_ENV=production
      - API_PORT=${API_PORT:-3000}
      - API_HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - rinha-network
    volumes:
      - ./logs:/app/logs

  # Payment worker service (if you need a separate worker)
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha-worker
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    command: ["npm", "run", "worker"]
    networks:
      - rinha-network

# Named volumes for data persistence
volumes:
  redis_data:
    driver: local

# Custom network for service communication
networks:
  rinha-network:
    driver: bridge