version: '3.8'

# Development overrides for docker-compose.yml
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-dependencies
    environment:
      - NODE_ENV=development
      - API_PORT=${API_PORT:-3000}
      - API_HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["npm", "run", "dev"]
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-dependencies
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["tsx", "watch", "src/workers/paymentWorker.ts"]
    volumes:
      - .:/app
      - /app/node_modules
